/**
 * Canonical structured-log event names.
 *
 * Every log line carries one of these as its `event` field so logs can be
 * filtered and alerted on without parsing free-text messages.
 */
export const LogEvent = {
  // Lifecycle
  BOT_STARTING: 'BOT_STARTING',
  BOT_READY: 'BOT_READY',
  BOT_SHUTDOWN: 'BOT_SHUTDOWN',
  CONFIG_LOADED: 'CONFIG_LOADED',
  CONFIG_CHANGED: 'CONFIG_CHANGED',

  // Voice
  VOICE_JOINED: 'VOICE_JOINED',
  VOICE_LEFT: 'VOICE_LEFT',
  VOICE_USER_STARTED: 'VOICE_USER_STARTED',
  VOICE_USER_STOPPED: 'VOICE_USER_STOPPED',
  VOICE_SEGMENT_READY: 'VOICE_SEGMENT_READY',
  VOICE_SEGMENT_DISCARDED: 'VOICE_SEGMENT_DISCARDED',
  VOICE_RECONNECTED: 'VOICE_RECONNECTED',
  VOICE_LIVENESS_WARNING: 'VOICE_LIVENESS_WARNING',
  DISCORD_VOICE_ERROR: 'DISCORD_VOICE_ERROR',

  // Speech-to-text
  TRANSCRIPTION_STARTED: 'TRANSCRIPTION_STARTED',
  TRANSCRIPTION_COMPLETED: 'TRANSCRIPTION_COMPLETED',
  TRANSCRIPTION_VERIFY: 'TRANSCRIPTION_VERIFY',
  STT_ERROR: 'STT_ERROR',
  STT_DEGRADED: 'STT_DEGRADED',
  STT_BREAKER_OPEN: 'STT_BREAKER_OPEN',
  STT_BREAKER_CLOSED: 'STT_BREAKER_CLOSED',

  // Moderation
  MODERATION_MATCH: 'MODERATION_MATCH',
  MODERATION_ACTION: 'MODERATION_ACTION',
  MODERATION_SKIPPED: 'MODERATION_SKIPPED',
  MODERATION_DEDUPED: 'MODERATION_DEDUPED',
  MODERATION_ERROR: 'MODERATION_ERROR',
  IDENTITY_MISMATCH: 'IDENTITY_MISMATCH',

  // Evidence
  EVIDENCE_SAVED: 'EVIDENCE_SAVED',
  EVIDENCE_ERROR: 'EVIDENCE_ERROR',
  EVIDENCE_PRUNED: 'EVIDENCE_PRUNED',
  EVIDENCE_ACCESSED: 'EVIDENCE_ACCESSED',
  EVIDENCE_DELETED: 'EVIDENCE_DELETED',

  // Permissions / commands
  PERMISSION_ERROR: 'PERMISSION_ERROR',
  COMMAND_INVOKED: 'COMMAND_INVOKED',
  COMMAND_DENIED: 'COMMAND_DENIED',

  // Storage
  STORAGE_ERROR: 'STORAGE_ERROR',
  STORAGE_PRUNED: 'STORAGE_PRUNED',
} as const;

export type LogEventName = (typeof LogEvent)[keyof typeof LogEvent];
